### ISSUE TITLE
flarum1.6.2不太稳定

### ISSUE THREAD

**Issue by FinKiin** [littlecxm/flarum-reply-to-see#4]
刷新有时能隐藏有时不能隐藏

**Comment by littlecxm** [comment]
在 1.6.3 中测试没有复现，详细步骤希望

**Comment by molinla** [comment]
我的版本是1.7.1，这个插件目前不生效，无论是管理员创建，还是普通用户创建。即使是游客都能看见隐藏的内容，我不知道应该提供什么信息，直接告诉我还需要补充的信息就OK的
这是我的插件列表
![image](https://user-images.githubusercontent.com/61045398/227563712-9177bfa3-07e0-47cf-b5a6-d37f951cf5b4.png)
这是我的帖子相关的权限截图
![image](https://user-images.githubusercontent.com/61045398/227564905-a2363e26-a3a2-488a-b633-6b80d7bc22e4.png)
最后是我作为游客访问需要回复才能查看的帖子的截图和开发者工具元素节点截图
![image](https://user-images.githubusercontent.com/61045398/227565863-f91e782f-cb0e-464d-9428-633b3fb0e02a.png)
如果还有需要我提供的信息，可以直接告诉我哈

**Comment by molinla** [comment]
经过的我的一轮测试，发现博客 blog 插件会导致 需要回复显示的内容直接显示出来 😂
![image](https://user-images.githubusercontent.com/61045398/227574470-d4641c4e-f5e7-427f-8b6f-f18e9b4073f2.png)
希望flarum加一个插件执行顺序的功能
附上一个正常运行的截图：
![image](https://user-images.githubusercontent.com/61045398/227574339-1fffd0ad-29c4-42c7-92f7-d3ed8d438590.png)
