### ISSUE TITLE
在flarum1.8版本中，需要任何人先评论一次后，这个隐藏框才能显示出来

### ISSUE THREAD

**Issue by HeapsortYi** [littlecxm/flarum-reply-to-see#5]
如题，像个bot一样测试了很多次后发现，这个神奇的功能必须通过别人先回复一次激活，才能顺利启用。。。
在有人回复之前，元素一直显示的是`<reply2see>隐藏的内容</reply2see>`，我瞎改了一下HideContentInPosts.php，发现正则表达式确实匹配上了，也替换了，但不知道为啥显示出来的还是原来的结果。。。。。

大佬可以帮帮看看是哪儿有问题吗，php和js小白真的无能为力了QAQ。。。救救孩子吧。。。

**Comment by littlecxm** [comment]
#4 
可以看看是不是其他插件导致的兼容问题？我在本地环境测试是正常的
<img width="881" alt="image" src="https://github.com/littlecxm/flarum-reply-to-see/assets/16154023/c82ff47a-07c9-4efd-bddf-0dbd6885440e">

**Comment by HeapsortYi** [comment]
> #4 可以看看是不是其他插件导致的兼容问题？我在本地环境测试是正常的 <img alt="image" width="881" src="https://user-images.githubusercontent.com/16154023/246345802-c82ff47a-07c9-4efd-bddf-0dbd6885440e.png">

你好大佬，感谢回复！
我真的不知道是哪个插件引起的QAQ。。。这是我所有插件列表：
<img width="1221" alt="image" src="https://github.com/littlecxm/flarum-reply-to-see/assets/19743449/0cbcd846-b1f4-4566-b2f1-2be037cdaef3">

Flarum版本是1.8.1，PHP版本是8.1.17。我看社区里也有人反馈不生效的问题，所以应该不是我一个人遇到了这个issue。。。
我现在别无他法，只能加一个15s执行一次的任务，检测回复可见后面有没有新评论，没有的话就自动发一个激活这个功能（很蠢但是真的没办法的方法）。。。希望大佬能看看是什么原因？或者发一下您的插件列表，我对比下可能是哪个插件导致的？（感觉会是BBcode类的插件？）

**Comment by littlecxm** [comment]
这是我目前在使用的插件
<img width="1330" alt="image" src="https://github.com/littlecxm/flarum-reply-to-see/assets/16154023/8f7220a6-582a-4f67-b5e6-60108bd37e88">

**Comment by HeapsortYi** [comment]
> 这是我目前在使用的插件 <img alt="image" width="1330" src="https://user-images.githubusercontent.com/16154023/246357704-8f7220a6-582a-4f67-b5e6-60108bd37e88.png">

hello大佬，我回报一下，冲突的插件是Prevent Double-Posting～
感觉是不是它把reply2see的替换结果覆盖了？还是不知道怎么就失效了。。。您要是有空的话可以看看，感谢感谢！
